name: Hide_FarmContent_From_Search

on:
  push:
    paths:
      - "nofarm_hosts.txt"
      - "AutoBuild/hide_farm.py"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run AutoBuild
        run: |
          cd AutoBuild
          python hide_farm.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add hide_farm_from_search.txt
          git add hide_farm_from_search_ff.txt
          git commit -m "🤖 自動更新 NoFarm"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.FUTAFILTERAUTOBUILD }}
